import Nav from "@/components/Nav";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import { ReactNode } from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="overscroll-none bg-blue-50">
        <Nav />
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
