name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    
    steps:
      - name: Pull Docker image
        run: sudo docker pull hyezoprk/apuu-next:latest
      - name: Delete Old docker container
        run: sudo docker rm -f apuu-next-container || true
      - name: Run Docker Container
        env:
          PORT: ${{ secrets.PORT }}
          NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
        run: >-
          sudo docker run -d
          -p $PORT:$PORT
          -e PORT=$PORT
          -e NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
          --network server
          --name apuu-next-container hyezoprk/apuu-next
      - name: Check Network Connection
        run: sudo docker network connect server apuu-next-container || true
