name: CI Pipeline

on:
  workflow_run:
    workflows: ["Playwright Tests"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build the Docker image
        env:
          PORT: ${{secrets.PORT}}
          NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
          TIPTAP_PRO_TOKEN: ${{ secrets.TIPTAP_PRO_TOKEN }}
        run: >-
          docker build
          --build-arg PORT=$PORT
          --build-arg NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
          --build-arg TIPTAP_PRO_TOKEN=$TIPTAP_PRO_TOKEN
          -t apuu-next .
      - name: taging
        run: docker tag apuu-next:latest ${{secrets.DOCKERHUB_USERNAME}}/apuu-next:latest
      - name: Push to Dockerhub
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/apuu-next:latest
