name: Playwright Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  playwright:
    name: "Playwright Tests"
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Configure .npmrc
        run: |
          echo "@tiptap-pro:registry=https://registry.tiptap.dev/" > ~/.npmrc
          echo "//registry.tiptap.dev/:_authToken=${{ secrets.TIPTAP_PRO_TOKEN }}" >> ~/.npmrc
          echo "shamefully-hoist=true" >> ~/.npmrc

      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key:
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{
            hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --production

      - name: Install playwright-merge-report
        run: pnpm install -D playwright-merge-html-reports

      - name: Build
        run: pnpm run build
        env:
          NEXT_PUBLIC_BASE_URL: ${{secrets.NEXT_PUBLIC_BASE_URL}}
          NEXT_PUBLIC_COLLAB_DOC_PREFIX: ${{secrets.NEXT_PUBLIC_COLLAB_DOC_PREFIX}}
          NEXT_PUBLIC_TIPTAP_COLLAB_APP_ID: ${{secrets.NEXT_PUBLIC_TIPTAP_COLLAB_APP_ID}}
          TIPTAP_COLLAB_SECRET: ${{secrets.TIPTAP_COLLAB_SECRET}}

      - name: Run Playwright tests
        run: pnpm run test
        env:
          HOME: /root
          CI: true
          NEXT_PUBLIC_BASE_URL: ${{secrets.NEXT_PUBLIC_BASE_URL}}
          NEXT_PUBLIC_COLLAB_DOC_PREFIX: ${{secrets.NEXT_PUBLIC_COLLAB_DOC_PREFIX}}
          NEXT_PUBLIC_TIPTAP_COLLAB_APP_ID: ${{secrets.NEXT_PUBLIC_TIPTAP_COLLAB_APP_ID}}
          TIPTAP_COLLAB_SECRET: ${{secrets.TIPTAP_COLLAB_SECRET}}
          TIPTAP_PRO_TOKEN: ${{secrets.TIPTAP_PRO_TOKEN}}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: playwright-report/

  deploy:
    needs: playwright
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
